zap: 
  debugFileName: "/Users/levi/go/src/project-gin-grpc/project-common/log/{app}/debug.log"
  infoFileName: "/Users/levi/go/src/project-gin-grpc/project-common/log/{app}/info.log"
  warningFileName: "/Users/levi/go/src/project-gin-grpc/project-common/log/{app}/warn.log"
  errorFileName: "/Users/levi/go/src/project-gin-grpc/project-common/log/{app}/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

mysql:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: gin # 数据库名称
  username: root # 用户名
  password: 123456 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  jwt_ttl: 43200